# Generated by Django 5.1.2 on 2024-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0005_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
