# Generated by Django 5.1.2 on 2024-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0006_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.TextField(),
        ),
    ]
