# Generated by Django 5.1.2 on 2024-10-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="title_tag",
            field=models.CharField(default="The Future Tech", max_length=100),
        ),
    ]
