# Generated by Django 5.1.2 on 2024-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_blogpost_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title_tag",
            field=models.CharField(max_length=200),
        ),
    ]
